# Generated by Django 4.2.4 on 2023-09-02 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0003_alter_kicks_kick_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 11, 21, 22, 107000)),
        ),
    ]
