# Generated by Django 4.2.4 on 2023-09-02 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0004_alter_kicks_kick_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='public_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 11, 30, 15, 479108)),
        ),
    ]
