# Generated by Django 4.2.4 on 2023-09-02 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0005_remove_post_date_post_public_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 11, 32, 11, 780)),
        ),
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(),
        ),
    ]
