# Generated by Django 4.2.4 on 2023-09-02 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0006_alter_kicks_kick_time_alter_post_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 11, 32, 34, 581138)),
        ),
    ]
