# Generated by Django 4.2.4 on 2023-09-02 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0010_alter_kicks_kick_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 12, 10, 6, 105766)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp4.author')),
            ],
        ),
    ]
