# Generated by Django 4.2.4 on 2023-09-05 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0017_alter_article_public_alter_comment_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 13, 40, 11, 963786)),
        ),
    ]
