# Generated by Django 4.2.4 on 2023-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nummer_tel',
            field=models.IntegerField(),
        ),
    ]
