# Generated by Django 4.2.4 on 2023-09-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='myapp5'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_more', models.ImageField(blank=True, upload_to='myapp5')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_more', to='myapp5.product')),
            ],
        ),
    ]
